Build before test

diff --git a/.github/workflows/slack-mainline.yml b/.github/workflows/slack-mainline.yml
--- a/.github/workflows/slack-mainline.yml
+++ b/.github/workflows/slack-mainline.yml
@@ -10,6 +10,25 @@ jobs:
   notification:
     runs-on: ubuntu-latest
     steps:
+      - uses: actions/checkout@v1
+      - run: npm ci
+      - run: npm run build
+      - run: npm run test
+      - name: check for uncommitted changes
+        # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
+        run: |
+          git diff --exit-code --stat -- . ':!node_modules' \
+          || (echo "##[error] found changed files after build. please 'npm run build && npm run format'" \
+                   "and check in all changes" \
+              && exit 1)
+      - name: check for uncommitted changes
+        # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
+        run: |
+          git diff --exit-code --stat -- . ':!node_modules' \
+          || (echo "##[error] found changed files after build. please 'npm run build && npm run format'" \
+                   "and check in all changes" \
+              && exit 1)
+              
       - name: Succeeded Check
         uses: ./
         with:
